name: Build Docker Image
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to build for (all)'
        required: true
        default: 'all'
env:
  GCR_KEY_FILE: ${{ secrets.GCR_KEY_FILE }}
  TARGET_ENV: ${{ github.event.inputs.env }}

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - name: dependencies cache
        id: deps-cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('package.json', 'yarn.lock', '.github/workflows/build-image.yaml') }}
      - name: install dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: |
          yarn
      - name: Build Image
        run: |
          echo "$GCR_KEY_FILE" | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev
          yarn build
          export TAG_NAME=${CI_COMMIT_TAG:-"v`git --no-pager log -1 --format="%ad" --date=format:"%Y%m%d"`-`git describe --always --dirty --abbrev=7`"}
          export IMAGE=us-central1-docker.pkg.dev/fifth-compiler-334213/alexgo/alex-monitor:$TAG_NAME
          docker build -t $IMAGE .
          docker push $IMAGE
